# Generated by Django 3.1.4 on 2021-02-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('CA', 'Collectibles & Art'), ('E', 'Electronics'), ('EM', 'Entertainment Memorabilia'), ('F', 'Fashion'), ('HG', 'Home & Garden'), ('M', 'Motors'), ('SG', 'Sporting Goods'), ('TH', 'Toys & Hobbies'), ('OC', 'Other Categories')], max_length=26)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
