# Generated by Django 3.1.4 on 2021-02-23 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210211_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('CA', 'Collectibles & Art'), ('E', 'Electronics'), ('EM', 'Entertainment Memorabilia'), ('F', 'Fashion'), ('Hg', 'Home & Garden'), ('M', 'Motors'), ('SG', 'Sporting Goods'), ('TH', 'Toys & Hobbies'), ('OC', 'Other Categories')], max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
