# Generated by Django 3.1.4 on 2021-02-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210223_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='ID',
            new_name='item_id',
        ),
    ]
