# Generated by Django 3.1.4 on 2021-02-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='ListComment',
        ),
    ]
