# Generated by Django 3.1.4 on 2021-02-24 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210224_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcomment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
